### ISSUE TITLE
Issue 도메인에 대해 리펙터링 한다

### ISSUE THREAD

**Issue by minsang-alt** [AgileHub-DQ/Backend#102]
### ✨ Describe

일관성이 떨어지는 코드에 대해 리펙터링을 진행합니다

### ✅ Tasks

- [x] Dto, Vo 클래스명 수정
- [x] dto 이너 클래스 쓰도록 수정
- [x] dto 패키지 만들고, 내부에 별도 request, response 패키지는 없애는 방향으로
- [x] service 레이어, query command 패키지로 나누기
- [x] repository 패키지 생성
- [x] static 클래스 사용 시 private 생성자로 생성 막기
