### ISSUE TITLE
프로젝트 생성,조회 API를 구현한다

### ISSUE THREAD

**Issue by minsang-alt** [AgileHub-DQ/Backend#30]
### ✨ Describe

Project 생성 및 Project들 조회 API를 구현합니다

### ✅ Tasks

- [x] 생성
    - [x] 컨트롤러
    - [x] 서비스
    - [x] 레포지토리
- [x] 조회
    - [x] 컨트롤러
    - [x] 서비스
    - [x] 레포지토리

### 🙋🏻 More
- [x] profile (local,prod,test)로 나누기
- [x] local : mysql 띄우고 data.sql 자동 실행 로직
- [x] test : h2 띄우기
- [x] prod : ddl-auto: none, schema.sql에 있는 ddl 직접 주입

_No response_
