### ISSUE TITLE
CI/CD를 위해 Github Actions workflow 파일을 작성한다

### ISSUE THREAD

**Issue by minsang-alt** [AgileHub-DQ/Backend#4]
### ✨ Describe

CI(지속적 통합, 빌드)와 CD(지속적 배포)를 위해 Github Actions를 활용해 workflow 파일을 작성합니다.

### ✅ Tasks

- [x] CI 테스트 workflow 작성
- [x] self-hosted 서버용 인스턴스 구성
- [x] CD workflow 작성

### 🙋🏻 More

https://azure-capston.atlassian.net/wiki/spaces/AT/pages/3702785/CI+CD+Github+Actions+self-hosted+runners
기존에 작성했던 글과 매우 비슷하게 만들 예정입니다
