### ISSUE TITLE
이슈 조회 쿼리를 분석하고 개선한다

### ISSUE THREAD

**Issue by minsang-alt** [AgileHub-DQ/Backend#60]
### 🔨 Describe

`spring.jpa.show-sql=true`
`spring.jpa.properties.hibernate.format_sql=true` 을 통해 API에서 발생할 수 있는 쿼리를 정리하고 실행계획을 이용해 개선이 필요한 원인들을 정리하겠습니다 

### ✅ Tasks

- [x] 각 프로젝트당 500 건의 이슈 생성 및 프로젝트 총 10_000개 즉  이슈 500만개의 더미데이터 생성 
- [x] 이슈쪽 API 쿼리가 어떻게 나가는 지 노션에 정리
- [x] 전체 이슈 조회 로직 완전히 바꾸기 , 프론트는 이미 작업 들어갔기 때문에 v2로 만들기
- [x] `EXPLAIN` 실행계획을 활용해 비효율적인 인덱스 처리를 하고 있는 지 확인
- [x] 성능 비교
- [x] 개선 후 컨플루언스에 정리
