### ISSUE TITLE
서버 api 도메인을 수정한다

### ISSUE THREAD

**Issue by minsang-alt** [AgileHub-DQ/Backend#67]
### 🔨 Describe

기존 api를 만들때 /api 로 시작했는데 어디에는 /api를 붙이고 하는 번거로움이 자주 생김. 따라서 www 하위도메인을 사용안하고
서버도메인은 api 하위도메인 사용함으로 /api가 아닌 /로 시작하도록 수정하겠습니다.

### ✅ Tasks

- [x] 가비아에서 `api.` 하위도메인 생성
- [x]  `nginx conf` 리버스 프록시 쪽 설정 수정
- [ ] 시큐리티 쪽 api 수정
- [ ] 전체 도메인 api 수정
