### ISSUE TITLE
이슈 테이블 칼럼 member_id에서 assignee_id로 이름 변경

### ISSUE THREAD

**Issue by minsang-alt** [AgileHub-DQ/Backend#79]
### 🔨 Describe

Issue Entity에서 변수명은 assignee로 제대로 정해져 있지만 DB칼럼명은 member_id로 되어있어 오해의 소지가 있습니다. 칼럼명을 따라서 assignee_id로 변경하겠습니다.
![image](https://github.com/AgileHub-DQ/Backend/assets/82764703/3dda7152-a205-4815-8d43-730634c47d0a)

### ✅ Tasks

- [ ] Issue Entity 클래스의 `member_id`를 `assignee_id`로 변경
- [x] DB 스키마 변경
- [ ] RDS에 해당 스키마로 적용 -> 프론트가 테스트 중이니 데이터를 지우지 말고 칼럼명만 바꾸는 식으로 하기

**Comment by minsang-alt** [comment]
assignee_id로 변경 시 해당 순서대로 실행하면 됩니다. 다만 수정하기 전 네이티브 쿼리, issue 클래스 여러 곳에서 member_id로 사용중이므로 모두 하나하나 찾아서 수정해야 합니다. 
```sql
ALTER TABLE issue
DROP FOREIGN KEY FKgj9b27brkevgyi6mit3uq92lp;

ALTER TABLE issue CHANGE member_id assignee_id bigint;

ALTER TABLE issue
ADD CONSTRAINT FKgj9b27brkevgyi6mit3uq92lp
FOREIGN KEY (assignee_id)
REFERENCES member (member_id);

```
